version: "3"

services:

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB2
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
  back:
    build: ./apache
    volumes:
      - ./src/check.php:/var/www/pr/check.php
      - ./src/private:/var/www/pr/private
      - ./conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database
  front:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - ./src/index.html:/usr/share/nginx/index.html
    depends_on:
      - back
volumes:
  db_volume:
