version: "3"

services:

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    links:
      - database
    ports:
      - 8000:80

  frontend:
    build:
      context: firstPrac
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - ./firstPrac/src:/var/www/html
    ports:
      - 8080:80

  main_page:
    build:
      context: secondPrac
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - ./secondPrac/src:/var/www/html
    ports:
      - 8081:80

  drawer:
    build:
      context: secondPrac
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - ./secondPrac/src:/var/www/html
    ports:
      - 8082:80

  sort:
    build:
      context: secondPrac
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - ./secondPrac/src:/var/www/html
    ports:
      - 8083:80