version: "3"

services:

  database:
    container_name: my_database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB2
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
  back:
    container_name: my_back
    build: ./apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/pr
      - ./conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - database
  front:
    container_name: my_front
    image: nginx
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/
    links:
      - back
  redis:
    container_name: my_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
volumes:
  db_volume:
  redis_volume:
